menu:
  image: base/icon.svg
  title: BacK To RooTs
  subtitle: Vuelta a la raíz
  items:
  # - label: INICIO
  #   link: /
  #   anchor: Back to Roots
  - label: CONÓCEME
    link: /#conoceme
  - label: QUÉ HAGO
    link: /#maestrias
    items:
    - label: DANZÁFRICA
      link: /danzafrica/
      anchor: Danza Africana en Cataluña
    - label: SATYAM YOGA
      link: /satyam-yoga/
      anchor: Clases de Satyam Yoga en Cataluña
    - label: AGUAHARA
      link: /aguahara/
      anchor: Sesiones de Aguahara en Cataluña
  - label: A DÓNDE TE LLEVO
    link: /#retiros
    items:
    - label: VIAJES
      link: /#viajes-senegal
      anchor: Viajes organizados a Senegal para mujeres
    - label: RETIROS
      link: /#retiros
      items:
      - label: REVAL
        link: https://www.vacacionesalternativas.es/
      - label: PARADISO RETREATS
        link: https://paradisoretreats.com/
  # - label: CONÓCETE
  #   link: /#conocete
  - label: CONTACTO
    link: /#contacto
    button: cta
  # - label: BLOG
  #   link: /blog/
callnows:
- type: custom
  link: https://wa.me/34677235334
  label: Coméntame lo que quieras, te leo
  icon: brand:whatsapp
  button: whatsapp
  lock: y
footer:
  color: dark
  space: 2
  div: brush
  div_x: n
  dots:
  - link: https://www.instagram.com/danafrimar/
  - link: https://www.linkedin.com/in/marta-ribas-918a643a/
  - link: https://www.facebook.com/marta.r.orozco.5
  - link: https://www.youtube.com/@back.toroots
  - link: https://g.page/r/CYztzzviHI_kEBM
  - link: https://g.page/r/CYu1Ude0qIvlEBM
    icon: place
  md: |
    - ::copyright::        {{< internal-link index >}}
    - ::balance::          {{< internal-link legal >}}
    - ::encrypted::        {{< internal-link privacy >}}
    - ::cookie::           {{< internal-link cookies >}}
    - ::brand:seacomoseo:: {{< i18n web_design >}} [seacomoseo.com](https://seacomoseo.com/)
    {.list-inline}
